name: Sync Branch

on:
  schedule:
    - cron: "0 0 * * *"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  sync-branch:
    name: Sync Branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git user
        run: |
          git config --global user.email "hirotomo.yamada@avap.co.jp"
          git config --global user.name "hirotomoyamada"

      - name: Merge branch
        run: |
          set -x
          git switch v2.0
          git merge main
          git push
